/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IngresosIndexRouteImport } from './routes/ingresos/index'
import { Route as IngresosNuevoRouteImport } from './routes/ingresos/nuevo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresosIndexRoute = IngresosIndexRouteImport.update({
  id: '/ingresos/',
  path: '/ingresos/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresosNuevoRoute = IngresosNuevoRouteImport.update({
  id: '/ingresos/nuevo',
  path: '/ingresos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ingresos/nuevo': typeof IngresosNuevoRoute
  '/ingresos': typeof IngresosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ingresos/nuevo': typeof IngresosNuevoRoute
  '/ingresos': typeof IngresosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ingresos/nuevo': typeof IngresosNuevoRoute
  '/ingresos/': typeof IngresosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ingresos/nuevo' | '/ingresos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ingresos/nuevo' | '/ingresos'
  id: '__root__' | '/' | '/ingresos/nuevo' | '/ingresos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IngresosNuevoRoute: typeof IngresosNuevoRoute
  IngresosIndexRoute: typeof IngresosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresos/': {
      id: '/ingresos/'
      path: '/ingresos'
      fullPath: '/ingresos'
      preLoaderRoute: typeof IngresosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresos/nuevo': {
      id: '/ingresos/nuevo'
      path: '/ingresos/nuevo'
      fullPath: '/ingresos/nuevo'
      preLoaderRoute: typeof IngresosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IngresosNuevoRoute: IngresosNuevoRoute,
  IngresosIndexRoute: IngresosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
